# Generated by Django 4.2 on 2024-01-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformationOverdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFO', models.IntegerField(max_length=5)),
                ('Unique', models.IntegerField(max_length=8)),
                ('NameClient', models.CharField(max_length=128)),
                ('Type', models.CharField(max_length=10)),
                ('Sum', models.FloatField(max_length=128)),
                ('StatusOverdue', models.IntegerField(max_length=1)),
                ('StatusWork', models.CharField(max_length=10)),
                ('StatusTurnover', models.CharField(max_length=10)),
            ],
        ),
    ]
