# Generated by Django 4.2 on 2024-01-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('sum', models.CharField(max_length=160)),
                ('all', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationOverdue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MFO', models.IntegerField()),
                ('Unique', models.IntegerField()),
                ('NameClient', models.CharField(max_length=128)),
                ('Type', models.CharField(max_length=10)),
                ('Sum', models.FloatField(max_length=128)),
                ('StatusOverdue', models.IntegerField()),
                ('StatusWork', models.CharField(max_length=10)),
                ('StatusTurnover', models.CharField(max_length=10)),
            ],
        ),
    ]
