# Generated by Django 4.2 on 2024-01-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationoverdue',
            name='MFO',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informationoverdue',
            name='StatusOverdue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='informationoverdue',
            name='Unique',
            field=models.IntegerField(),
        ),
    ]
